//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEC06.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class YYTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal YYTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OEC06.App_GlobalResources.YYTranslations", typeof(YYTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return to List.
        /// </summary>
        public static string backToList {
            get {
                return ResourceManager.GetString("backToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Phone.
        /// </summary>
        public static string cellPhone {
            get {
                return ResourceManager.GetString("cellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cell phone must have 10 digits (including area code).
        /// </summary>
        public static string cellPhoneDigits {
            get {
                return ResourceManager.GetString("cellPhoneDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        public static string county {
            get {
                return ResourceManager.GetString("county", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Farm.
        /// </summary>
        public static string CreateNewFarm {
            get {
                return ResourceManager.GetString("CreateNewFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Joined must be given if Last Contact Date is given.
        /// </summary>
        public static string dataJoinedMustBeGiven {
            get {
                return ResourceManager.GetString("dataJoinedMustBeGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Joined.
        /// </summary>
        public static string dateJoined {
            get {
                return ResourceManager.GetString("dateJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception on delete: .
        /// </summary>
        public static string deleteException {
            get {
                return ResourceManager.GetString("deleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string direction {
            get {
                return ResourceManager.GetString("direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm.
        /// </summary>
        public static string farm {
            get {
                return ResourceManager.GetString("farm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm cannot be contacted about plots before they have joined the program.
        /// </summary>
        public static string FarmCannotBeContactedBeforeJoin {
            get {
                return ResourceManager.GetString("FarmCannotBeContactedBeforeJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm ID.
        /// </summary>
        public static string farmId {
            get {
                return ResourceManager.GetString("farmId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm Listing.
        /// </summary>
        public static string farmListing {
            get {
                return ResourceManager.GetString("farmListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farms.
        /// </summary>
        public static string farms {
            get {
                return ResourceManager.GetString("farms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field &apos;{0}&apos; must be a date.
        /// </summary>
        public static string FieldMustBeDate {
            get {
                return ResourceManager.GetString("FieldMustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field &apos;{0}&apos; must be a number.
        /// </summary>
        public static string FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string homePhone {
            get {
                return ResourceManager.GetString("homePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home phone must have 10 digits (including area code).
        /// </summary>
        public static string homePhoneDigits {
            get {
                return ResourceManager.GetString("homePhoneDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception on insert:.
        /// </summary>
        public static string insertException {
            get {
                return ResourceManager.GetString("insertException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Contact Date.
        /// </summary>
        public static string lastContactDate {
            get {
                return ResourceManager.GetString("lastContactDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at least one of town or county must be provided.
        /// </summary>
        public static string oneTownOrCountyShouldBeProvided {
            get {
                return ResourceManager.GetString("oneTownOrCountyShouldBeProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string postalCode {
            get {
                return ResourceManager.GetString("postalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should match canadian postal Code pattern (eg. N2C 2H7) .
        /// </summary>
        public static string postalCodeReg {
            get {
                return ResourceManager.GetString("postalCodeReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string provinceCode {
            get {
                return ResourceManager.GetString("provinceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the length of province code can only be 2 .
        /// </summary>
        public static string provinceCodeLength {
            get {
                return ResourceManager.GetString("provinceCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the province code can only be letters.
        /// </summary>
        public static string provinceCodeLetter {
            get {
                return ResourceManager.GetString("provinceCodeLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should match canadian province code pattern (eg. ON).
        /// </summary>
        public static string provinceCodeReg {
            get {
                return ResourceManager.GetString("provinceCodeReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to province code &apos;{0}&apos; is not on file.
        /// </summary>
        public static string provinceNotOnFile {
            get {
                return ResourceManager.GetString("provinceNotOnFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the farm &apos;{0}&apos; has been deleted successfully.
        /// </summary>
        public static string recordDeletedForX {
            get {
                return ResourceManager.GetString("recordDeletedForX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one new record inserted for &apos;{0}&apos;.
        /// </summary>
        public static string recordInsertedForX {
            get {
                return ResourceManager.GetString("recordInsertedForX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record uptated for &apos;{0}&apos;.
        /// </summary>
        public static string recordUpdatedForX {
            get {
                return ResourceManager.GetString("recordUpdatedForX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a non-blank &apos;{0}&apos; is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string selectlanguage {
            get {
                return ResourceManager.GetString("selectlanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string town {
            get {
                return ResourceManager.GetString("town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception on update:.
        /// </summary>
        public static string updateException {
            get {
                return ResourceManager.GetString("updateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be in the future.
        /// </summary>
        public static string XDateCannotBeInFuture {
            get {
                return ResourceManager.GetString("XDateCannotBeInFuture", resourceCulture);
            }
        }
    }
}
